### ISSUE TITLE
Blurry tray icon

### ISSUE THREAD

**Issue by kindlyfire** [RoyalSloth/SlothTracker#1]
I really like this time tracker.

One thing I noticed though is the blurry tray icon, like this:

![Screenshot_20200320_105416](https://user-images.githubusercontent.com/10267586/77153016-4649be80-6a99-11ea-9f4b-c60b0978b189.png)

I'm running the lastest KDE Neon version and installed SlothTracker from the .deb file.

**Comment by RoyalSloth** [comment]
Thanks for the bug report and kind words.

Unfortunately the toolkit does not support displaying .svg icons for the tray and launcher, so I have to use .png which do get blurry if the displayed icon is too small or too large (and has to be either shrinked or enlarged).

Do you mind telling me your screen resolution and measuring the height of the icon in the bar? From the screenshot I measured 24px, but I don't know if that's actually the case. On KDE you can use KRuler for that.

On XFCE it looks a bit better (but it depends on the height of the bar as well):
![image](https://user-images.githubusercontent.com/60410333/77191621-7e71f100-6adb-11ea-8109-a35caecefd96.png)

**Comment by kindlyfire** [comment]
I see. My screen resolution is 1920x1080 with no scaling. The icon seems to be 20px wide, and I can't seem to get its height (due to KRuler not being able to move itself above the task bar). The task bar itself is 36px in height though.

**Comment by RoyalSloth** [comment]
Apparently this is a known issue in the KDE community: https://wiki.archlinux.org/index.php/KDE#Blurry_icons_in_System_tray

I wrote a workaround that solves this issue which will be part of v1.4.3 (coming out soon):
![image](https://user-images.githubusercontent.com/60410333/77235497-6d49e280-6bb6-11ea-932b-99dcb72e3f0d.png)

As recommended in the link above, you will have to install `libappindicator-gtk3`.

**Comment by RoyalSloth** [comment]
Patch v1.4.3 was published and the problem should be fixed. Closing.
